import {
  login,
  tokenRequest,
  requestStarted,
  requestFail,
  fetchToken,
  getName,
  getEmail } from './login';
import {
  gravatarRequestStarted,
  gravatarRequest,
  gravatarRequestFail,
  fetchGravatar,
  changeQuestionNumber,
  changeButtonStyle,
  resetClasses,
  resetScore,
  resetQuestion,
  disableOptions,
  enableOptions,
  enableButton,
  disableButton,
  updateScore,
  saveTimer } from './gamepage';

export default {
  login,
  tokenRequest,
  requestStarted,
  requestFail,
  fetchToken,
  gravatarRequestStarted,
  gravatarRequest,
  gravatarRequestFail,
  getName,
  fetchGravatar,
  changeQuestionNumber,
  getEmail,
  changeButtonStyle,
  resetClasses,
  resetScore,
  resetQuestion,
  disableOptions,
  enableOptions,
  enableButton,
  disableButton,
  updateScore,
  saveTimer,
};
